### ISSUE TITLE
Release creation fails when `token` is empty

### ISSUE THREAD

**Issue by manferlo81** [manferlo81/action-auto-release#6]
When used like...

```yaml
steps:
  - name: Create GitHub Release
    uses: manferlo81/action-auto-release@v0
    with:
      token: ""
```

... it will throw
